module.exports = {
  customSyntax: 'postcss-scss',
  ignoreFiles: [
    '_sass/common/classes/_APlayer.min.scss',
  ],
  extends: [
    'stylelint-config-standard',
    'stylelint-config-recommended-scss',
  ],
  rules: {
    'at-rule-empty-line-before': null,
    'at-rule-no-vendor-prefix': null,
    'alpha-value-notation': null,
    'block-no-empty': null,
    'color-function-notation': null,
    'color-hex-length': null,
    'comment-whitespace-inside': null,
    'comment-empty-line-before': null,
    'declaration-empty-line-before': null,
    'declaration-block-single-line-max-declarations': null,
    'font-family-name-quotes': null,
    'function-url-quotes': null,
    'import-notation': null,
    'keyframes-name-pattern': null,
    'length-zero-no-unit': null,
    'media-feature-range-notation': null,
    'no-descending-specificity': null,
    'no-duplicate-selectors': null,
    'no-empty-source': null,
    'no-invalid-position-at-import-rule': null,
    'number-max-precision': null,
    'property-no-deprecated': null,
    'property-no-vendor-prefix': null,
    'rule-empty-line-before': null,
    'scss/at-extend-no-missing-placeholder': null,
    'scss/at-if-no-null': null,
    'scss/comment-no-empty': null,
    'scss/no-global-function-names': null,
    'selector-class-pattern': null,
    'selector-id-pattern': null,
    'selector-not-notation': null,
    'selector-no-vendor-prefix': null,
    'selector-pseudo-element-colon-notation': null,
    'shorthand-property-no-redundant-values': null,
    'value-no-vendor-prefix': null,
    'value-keyword-case': null,
  },
};
